name: Infracost

on:
  pull_request:   # Запускати на кожному Pull Request
    branches:
      - main

jobs:
  infracost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Terraform init
        run: terraform init

      - name: Generate Infracost cost estimate baseline
        run: infracost breakdown --path=. --format=json --out-file=/tmp/infracost-base.json

      - name: Comment PR with cost estimate
        uses: infracost/actions/comment@v2
        with:
          path: /tmp/infracost-base.json
          behavior: update
