name: Infracost

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  infracost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Terraform init
        run: terraform init

      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

      - name: Generate Infracost cost estimate
        run: |
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > plan.json
          infracost breakdown --path plan.json --format github-comment --show-skipped --out-file infracost-comment.json
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      - name: Post Infracost comment
        uses: infracost/actions@v3
        with:
          path: infracost-comment.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
