name: Infracost

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  infracost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run Terraform init
        run: terraform init

      - name: Generate Infracost cost estimate
        uses: infracost/infracost-gh-action@v2
        with:
          path: .
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
