name: Infracost

on:
  pull_request:
    branches:
      - main

jobs:
  infracost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

      - name: Authenticate with Infracost
        run: infracost auth login --api-key ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost breakdown
        run: |
          terraform init
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > plan.json
          infracost breakdown --path plan.json --format github-comment --show-skipped --out-file infracost-comment.json

      - name: Post Infracost comment
        uses: infracost/actions@v3
        with:
          path: infracost-comment.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
